---
# tasks file for docker | EL Family

- name: EL Family | Installing {{ docker_centos_pre_reqs }}
  become: true
  ansible.builtin.yum:
    name: "{{ docker_centos_pre_reqs }}"
    state: "{{ docker_centos_pre_reqs_desired_state }}"
    update_cache: yes

- name: EL Family | Adding stable repository for {{ docker_repo_centos }}
  become: true
  ansible.builtin.yum_repository:
    name: "{{ docker_repo_centos_name }}"
    description: "{{ docker_repo_centos_description }}"
    baseurl: "{{ docker_repo_centos }}"
    gpgcheck: "{{ docker_repo_centos_gpgcheck }}"
    gpgkey: "{{ docker_repo_gpg_key }}"
    file: "{{ docker_repo_centos_filename }}"
    state: "{{ docker_repo_centos_desired_state }}"
    enabled: "{{ docker_repo_centos_enabled }}"

- name: EL Family | Installing {{ docker_apps }}
  become: true
  ansible.builtin.yum:
    name: "{{ docker_apps }}"
    state: "{{ docker_apps_desired_state }}"
    update_cache: yes
  notify:
    - "set_{{ docker_service_name }}_service_state"
    - "set_{{ docker_service_name }}_service_boot_state"
