name: build-and-test

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'feature*'
      - 'feature_*'
      - 'feature/*'
      - 'hotfix/*'
      - 'hotfix*'
      - 'master'
  schedule:
    - cron: '0 14 * * *'


jobs:

  code_quality:

    name: SonarCloud Code Quality Check
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        path: 'darkwizard242.docker'
        fetch-depth: 0

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: 'darkwizard242.docker'
        args: >
          -Dsonar.projectVersion=${{ github.ref }}_${{ github.run_number }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build:

    name: Build & Test
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 6
      matrix:
        IMAGE: [ubuntu-18.04, centos-7, debian-buster, debian-stretch]

    steps:

    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        path: 'darkwizard242.docker'

    - name: Set up Python 3.10.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0

    - name: Update repo cache, install python3-setuptools and required pip modules
      run: |
        sudo apt-get update
        sudo apt-get install python3-setuptools -y
        pip3 install -U pip wheel ansible molecule[docker] docker ansible-lint flake8 pytest-testinfra

    - name: Execute Molecule test of role for ${{ matrix.IMAGE }}
      working-directory: 'darkwizard242.docker'
      run: DISTRO=${{ matrix.IMAGE }} molecule test
      env:
        PY_COLORS: '1'
        ANSIBLE_FORCE_COLOR: '1'
