name: release

on:
  push:
    tags:
      - '*'

jobs:

  release:

    name: Release
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        path: 'darkwizard242.docker'

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Update repo cache, install python3-setuptools and required pip modules
      run: |
        sudo apt-get update
        sudo apt-get install python3-setuptools -y
        pip3 install -U pip wheel ansible

    - name: Import to Ansible Galaxy.
      working-directory: 'darkwizard242.docker'
      run: ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} ${{ github.repository_owner }} $(echo ${{ github.repository }} | sed 's/.*\///')
